DCID_SAVE_PATH:
  JSON_FILE_PATH: "data/dcids.json"

VECTORDB:
  BASE_DATABASE_PATH: "data/DataCommonsDB2"
  COLLECTION_NAME: "datacommons_stats2"
  EMBEDDING_MODEL_NAME: "text-embedding-3-small"
  BATCH_SIZE: 200